#FROM ubuntu:24.04
FROM ubuntu:24.04

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHON_ENV=/opt/venv
ENV PATH="$PYTHON_ENV/bin:$PATH"

RUN apt update && apt install -y \
    python3 python3-pip python3-venv curl wget ca-certificates libpq-dev gcc && \
    python3 -m venv $PYTHON_ENV

COPY requirements.txt /app/

RUN pip install --no-cache-dir --upgrade -r requirements.txt

ARG CACHEBUST=1

COPY . /app/

EXPOSE 8000

ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--proxy-headers", "--reload"]